baseURL: "https://rivkanexus.github.io/ISPA-DRC/"
title: ISPA DRC.cd
paginate: 12
theme: ["hugobricks"]
defaultContentLanguage: fr
assetDir: static

markup:
  goldmark:
    renderer:
      unsafe: true # Allow HTML in md files

languages:
  en:
    languageName: English
    contentDir: content/en
    languageCode: en
    weight: 2
    disabled: false
  fr:
    languageName: French
    contentDir: Content/fr
    languageCode: fr
    weight: 1
    disabled: false