baseURL: "https://github.com/Rivkanexus/ISPADRC/"
title: ISPA DRC.cd
paginate: 12
theme: ["hugo-notice", "hugobricks"]
defaultContentLanguage: fr
defaultContentLanguageInSubdir: false
assetDir: static

markup:
  goldmark:
    renderer:
      unsafe: true # Allow HTML in md files
      tableOfContents:
    startLevel: 1

languages:
  en:
    languageName: English
    contentDir: content/en
    weight: 2
    disabled: false
  fr:
    languageName: French
    contentDir: Content/fr
    weight: 1
    disabled: false