name: Push to GitHub Pages on push to main
on:
  push:
    branches:
      - main

  jobs:
   build:
      name: Deploy
      runs-on: ubuntu-latest
  steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Deploy the site
      uses: Rivkanexus/ISPA-DRC/hugo-deploy-gh-pages@main
  env:
        HUGO_VERSION: 0.120.4
        TARGET_REPO: github.com/Rivkanexus/ISPA-DRC.git
        TARGET_BRANCH: main
        TOKEN: ${{ secrets.TOKEN }}
        HUGO_ARGS: '-t academic'
        CNAME: Rivkanexus.github.io